### ISSUE TITLE
Tag accidentally closed to early

### ISSUE THREAD

**Issue by stephanrauh** [NoSoup4you2/PDFViewer11#1]
Hi Soup, :)

there's a tiny typo in this line: 
https://github.com/NoSoup4you2/PDFViewer11/blob/be7cdaa6ca73dee4a991e4557c324c1683cb7fd6/src/app/app.component.html#L5

Remove the trailing ">", and everything works fine.

Best regards,
Stephan

**Comment by NoSoup4you2** [comment]
Thanks that was it, after so many copy and past and reedits around the Angular 13 and stack blitz issue
This closing tag must have come from the editor

From: Stephan Rauh ***@***.***>
Sent: Saturday, May 7, 2022 2:02 AM
To: NoSoup4you2/PDFViewer11 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NoSoup4you2/PDFViewer11] Tag accidentally closed to early (Issue #1)


Hi Soup, :)

there's a tiny typo in this line:
https://github.com/NoSoup4you2/PDFViewer11/blob/be7cdaa6ca73dee4a991e4557c324c1683cb7fd6/src/app/app.component.html#L5

Remove the trailing ">", and everything works fine.

Best regards,
Stephan

**Comment by stephanrauh** [comment]
You're welcome!
